### PR TITLE
Adds ability to use a unique ID per set of credentials

### LINKED ISSUE #218: Generate unique ID for each set of credentials
So, right now, we generate a unique encryption key for each site key (facebook, twitter, etc). These encryption keys are used to encrypt credentials on _all_ of your devices and they never change.

We're going to fix the never change thing with #185 (I've made a little progress on it), but is there a reason why we'd want these keys (even when rotated) to remain consistent across all devices?

I propose the following idea:
1. User inputs a new set of credentials and we are given `siteKey`, `username`, `password
2. waltzio/waltz generates a pseudo-random `credentialID,` which is uses as the identifier when requesting a new encryption key from waltzio/cy
3. waltzio/cy returns an `encryptionKey` that matches the `credentialID`
4. waltzio/waltz encryptions `password` with `encryptionKey`
5. waltzio/waltz stores under `siteKey` in the credentials object in local storage:

``` javascript
{
    id: credentialID,
    password: crypto.encrypt(password, encryptionKey),
    username: username
}
```
1. The next time user logs in with `siteKey`, we look up the credentials that match `siteKey`, pull out the appropriate `credentialID` and use that to get the correct `encryptionKey` from waltzio/cy

With this new scheme, we get a few benefits (I _think_ they are benefits at least):
- passwords are encrypted with different keys across different devices
- if you delete your credentials from a computer, then reencrypt, you get an automatic key rotation because the credentialID will change

thoughts @landakram @josephwegner

### PR DESCRIPTION
**Pull request by jessepollak**
Would close #218 if merged.

This PR also includes a refactoring of the code that interacts with waltzio/cy in waltzio/waltz.

Right now, this generates a 13 character ID like `clxb39578ehfr` and uses that to get a new key from waltzio/cy.

Possible changes we could make:
- append the siteKey to the beginning, so the credentialID that waltzio/cy would see would be like `facebook_ clxb39578ehfr`

### CODE REVIEW

**Comment by landakram** [comment]
LGTM, but I haven't pulled to test or anything.

**Comment by josephwegner** [comment]
comments left inline on the commit..

**Comment by jessepollak** [comment]
Wooo! We have our first tests!

**Comment by jessepollak** [comment]
To run them, just open up the SpecRunner.html file, which is in the tests/ folder.

**Comment by jessepollak** [comment]
Merging :/

**Pull request merged**
