### PR TITLE
Feature rebrand

### PR DESCRIPTION
**Pull request by josephwegner**
@jessepollak @brennenbyrne Can you look at this and merge it if you think it's good?

### CODE REVIEW

**Comment by josephwegner** [comment]
Oh, just give me your thoughts - I can do the merge, since there are conflicts.  My bad.

**Comment by jessepollak** [comment]
Everything looks good to me

:shipit:

**Comment by jessepollak** [comment]
One thing is that I think delete should be moved out from under the decrypt click.

**Comment by josephwegner** [comment]
That sounds fine.  I will create a separate ticket for it.

**Pull request merged**
