### PR TITLE
wordpress.com

### PR DESCRIPTION
**Pull request by lolux**
Adding wordpress.com to site_configs. (Forget the other one if you want to . . . my moodle site.)

### CODE REVIEW

**Comment by jessepollak** [comment]
Hmmm, any chance we could get this repulled from develop on your side @lolux? I don't want to add all those ugly commits into our develop tree.

You can do this by checking out develop (not master) in your repository, then checking out a new branch and adding the correct configs.

Let me know if that's OK!

**Comment by jessepollak** [comment]
You  might have to close this PR and open another one.

**Comment by lolux** [comment]
[Doh! Adding self pull request for mandatory personal Git tutoring session
with Jesse!]

Okay, second try on the way. . .

**Comment by jessepollak** [comment]
Thanks Laurence!

**Pull request closed without merging**
