### PR TITLE
Add wordpress.com

### PR DESCRIPTION
**Pull request by lolux**

### CODE REVIEW

**Comment by jessepollak** [comment]
This looks pretty good, for the login URLS, can you add: https://en.wordpress.com/wp-login.php as the first one. Not sure you need the others. 

I'm going to test it out tomorrow and then merge.

**Comment by lolux** [comment]
Couple things:

First, I decided to close this pull in order to start with an English-only version (pull coming soon).

Second, here is the complete list of language-specific WP sub-domains. Each one has its own wp-login.php:

```
            "urls": ["https://ar.wordpress.com/wp-login.php","https://az.wordpress.com/wp-login.php","https://bg.wordpress.com/wp-login.php","https://bn.wordpress.com/wp-login.php","https://ca.wordpress.com/wp-login.php","https://cs.wordpress.com/wp-login.php","https://da.wordpress.com/wp-login.php","https://de.wordpress.com/wp-login.php","https://el.wordpress.com/wp-login.php","https://en.wordpress.com/wp-login.php","https://es.wordpress.com/wp-login.php","https://et.wordpress.com/wp-login.php","https://fa.wordpress.com/wp-login.php","https://fi.wordpress.com/wp-login.php","https://fr.wordpress.com/wp-login.php","https://fr-ca.wordpress.com/wp-login.php","https://gl.wordpress.com/wp-login.php","https://gu.wordpress.com/wp-login.php","https://he.wordpress.com/wp-login.php","https://hi.wordpress.com/wp-login.php","https://hr.wordpress.com/wp-login.php","https://hu.wordpress.com/wp-login.php","https://id.wordpress.com/wp-login.php","https://it.wordpress.com/wp-login.php","https://ja.wordpress.com/wp-login.php","https://ka.wordpress.com/wp-login.php","https://km.wordpress.com/wp-login.php","https://kn.wordpress.com/wp-login.php","https://ko.wordpress.com/wp-login.php","https://kk.wordpress.com/wp-login.php","https://lv.wordpress.com/wp-login.php","https://lt.wordpress.com/wp-login.php","https://mn.wordpress.com/wp-login.php","https://ms.wordpress.com/wp-login.php","https://nl.wordpress.com/wp-login.php","https://no.wordpress.com/wp-login.php","https://pl.wordpress.com/wp-login.php","https://pt.wordpress.com/wp-login.php","https://pt-br.wordpress.com/wp-login.php","https://ro.wordpress.com/wp-login.php","https://ru.wordpress.com/wp-login.php","https://sk.wordpress.com/wp-login.php","https://sl.wordpress.com/wp-login.php","https://sq.wordpress.com/wp-login.php","https://sr.wordpress.com/wp-login.php","https://sv.wordpress.com/wp-login.php","https://ta.wordpress.com/wp-login.php","https://th.wordpress.com/wp-login.php","https://tl.wordpress.com/wp-login.php","https://tr.wordpress.com/wp-login.php","https://uk.wordpress.com/wp-login.php","https://vi.wordpress.com/wp-login.php","https://zh-cn.wordpress.com/wp-login.php","https://zh-hk.wordpress.com/wp-login.php","https://zh-tw.wordpress.com/wp-login.php"],
```

I'm going to do some more testing on a multi-lingual version. (Is this even possible? Do we need individual .json's for each one?)

**Comment by jessepollak** [comment]
Hmm, I'd make it with just the english one in the urls for now.

**Comment by jessepollak** [comment]
If you pull that, I'll try it out today and give you feedback.

**Comment by lolux** [comment]
Presently pulling my hair out trying to properly pull this to you:
https://github.com/lolux/waltz/blob/lolux_site_configs/site_configs/wordpress-en.json

**Pull request closed without merging**
