### PR TITLE
Make Waltz work universally

### PR DESCRIPTION
**Pull request by landakram**
This PR makes Waltz work on sites without site configs. This means: 
- Waltz detects login forms and displays the button when something looks like a login form
- For "anonymous" sites, or sites without site configs, _all_ cookies are deleted from the base domain on logout
- Logins are acknowledged as successful when visiting a page that doesn't have a login form

In addition, instead of using timers, this PR changes waltz.js to use [DOM Mutation Observers](https://code.google.com/p/mutation-summary/) to detect login fields and the logged-in check. This means Waltz can be loaded before `$(document).ready` and the button displayed as soon as possible. It also means Waltz works on ajax-y pages that dynamically load login form elements after the page is loaded.

There are a few issues that should be addressed, however: 
- Waltz button will show even when login forms are hidden (i.e. on a wordpress login page with Clef enabled) 
  - This is because `findLoginForm` finds even hidden login forms. Do we want it to only find login forms that are shown? 
- Waltz overlay flashes when logging into some sites (for an example, see [npr.org](http://npr.org))
  - This is because `kickedOff` is unset before a login. I did this so that ajax errors are correctly detected (for examples, try logging in to [crashlytics.com](http://crashlytics.com) or [pandora.com](http://pandora.com) with bad credentials). However, it might be worthwhile to remove this or implement it differently, since I'm not sure how many sites are affected by Waltz flashing vs. how many use ajax logins.
- I haven't widely tested it. The sites I have tested on worked fine, but I'm sure there will be cases where it doesn't work correctly. But hey, Waltz _finally_ works on iTunes Connect, which, let's be honest, was my ultimate goal here.

### CODE REVIEW

**Comment by jessepollak** [comment]
A few thoughts:
- Waltz should definitely only show when login forms are visible. You should be able to use the `:visible` selector or something like that to achieve this. Perhaps listen for the form to be added to DOM and then start a timeout checking for whether it's visible?
- When you say Waltz overlay, do you mean that actual Clef overlay or just the Waltz button. If it's just the Waltz button, I'd say that it's fine.

:clap:

**Comment by josephwegner** [comment]
@landakram @jessepollak When we first built Waltz we used a heuristics design like this to guess at login forms and try to fill them. We decided against it because it leaves too many holes for bad user experience.

What changed your minds?

Also, did you reuse any of the old code from that system, or start from scratch. The method I was using in the original build was based on something I did at a previous employer, and was pretty well battle tested.

**Comment by landakram** [comment]
Here was my thinking: 

When we first built Waltz, the holes in UX were mostly around logout, since we thought it wasn't possible to build a consistent user experience where every site that you're logged into was also logged out through Waltz. In thinking about it more, this was actually easy to workaround — I just delete all cookies on the domain indiscriminately. 

Technical limitations aside, the majority of users' feedback says that they're limited by the fact that they can't use it for one-off sites. This has also been my personal experience after using Waltz regularly for ~6 months. More often than not, I actually do remember my passwords for facebook, gmail, and other big sites because I use them more often. The smaller sites that I log into every once in a while, however, are the real culprit when it comes to forgetting passwords. I'd rather have a slightly less consistent user experience (for example, for non-site-config sites, you can only log in on pages where there is a login form) in favor of being able to use Waltz in these places, without the manual effort of having to create a site config.

I still think site configs are useful, especially for the sites where we think being able to log in on any page _really_ adds a lot of value (and for the beautiful page of sites where you can use Waltz). I'd love to build a community around adding site configs, but the manual labor of doing it ourselves hampers getting it in more places that people can use. I think their usefulness will really be when the login form detection fails. 

What do you think about that? 

I _did_ use the old code, almost verbatim, but changed a few things as I read through and understood it. Notably, I only detect `form` elements, since we don't currently handle submitting anything other than a form. It works great!

**Comment by josephwegner** [comment]
For the record, the original conversation was #34, and the turning point of the discussion was @jessepollak's comment: https://github.com/waltzio/waltz/issues/34#issuecomment-26310651 (which references the very important #39)

It sounds like we are making the decision to disregard the decisions we made then. Waltz will lose some "magic" and feel more like a regular 'ol password manager.

That's a decision I'm OK with. We built Waltz a long time ago, and the user feedback seems to be indicating that global usability is more important than magic (sort of the same problem Waltz set out to solve for Clef).

I just want to be clear that we're deciding here to change the vision of Waltz. If we're not cool with that, then this PR shouldn't go in.

**Comment by josephwegner** [comment]
I also want to point out that I am knowingly bike shedding right now. It's no secret that I haven't actively developed anything on Waltz in a long time. I have strong opinions about Waltz's direction, but ultimately you guys can override whatever I say, because you've got more skin in the game.

**Comment by jessepollak** [comment]
The real thing with Waltz (and Clef, really) is that people love it but they will only use it if they can use it in multiple places. In our analytics, we can see a direct correlation between the number of sites that a user users Clef on and their long-term retention on our platform. Someone who uses Clef on 10+ sites is 3-4x more likely to be around in a month than someone who uses it on 2 or 3. 

We think we'll be able to provide a comparable experience with Mark's changes as we've been providing, and we think it's going to increase the number of places people use Waltz pretty drastically (as Mark says, those one-time use sites are the places where something like this is often most valuable). For us, the potential small trade-off in experience is worth that gain.

Looking at this situation, I realize that we should have re-opened this up as public issue before writing the code to make the change — definitely not the open source way. To be honest, we've just been really heads down building and growing for the last few months and this has been a decision that's been incubating internally for a while. Mark took a lead on it this week and we figured we'd give it a go.

:8ball:

**Comment by josephwegner** [comment]
:+1:

**Comment by landakram** [comment]
I definitely should have opened up a public discussion before opening up this PR. I'm sorry about that. I started exploring what a universal Waltz would look like late last week, and then just rolled with it since I got more and more excited as I started implementing. I didn't mean to steamroll discussion of what we want Waltz to be.

Without site configs, we definitely lose some of the magic. In our original vision, site configs allowed us to think about additional features sets like registration that are more closely tied to the site. They also allowed us to log in from any page. In practice, we are a small group of contributors with limited resources. Registration and other features that separate Waltz from a traditional password manager are still things that I think we _should_ do and are really only possible with site configs. But I also know that we all want to see Waltz grow since we've put a lot of love into it. I want Waltz to be somewhere in between — better, more magical than a traditional password manager (with the potential to provide even better features through site configs) but still just as universally useful. 

I do think that universal Waltz provides a comparable experience to Waltz now (I know this is a small point, but cloning the input fields and filling those in instead of the visible input fields makes a big difference in making it feel different from a password manager). We'll likely have false negatives where Waltz does not correctly detect login forms, but I'd rather put Waltz in the position where users are requesting that it works on 2 of the 25 sites they use to log in, rather than 20 of the 25 and waiting on us, you know?

**Comment by josephwegner** [comment]
OK, I dig.

One question, though - is this going to be really confusing for a user?

Most password managers are pretty obvious - you go to a page that has a login form, it fills in the password for you, and then you submit the form. It's pretty easy to understand because you're actually _seeing_ what's happening. You can pretty easily figure out the "rules" of the app just by using it.

Waltz is different, but up until now it's still been fairly easy to observe its "rules". You go to a site that supports Waltz, see the Waltz button, click it, and then you're logged in. Assuming the magic of Waltz has been clear to users, part of their mental mapping of the "rules" is that they can do this from any page.

These changes increase the complexity significantly. There is no longer a standard rule set that applies everywhere for Waltz. It behaves differently depending on if you're on a site that has a site config, which is something that the average user will have absolutely no context for understanding. It may be more useful, but users are often afraid of things they don't understand (especially relating to passwords).

I don't bring this up to say that we shouldn't add the feature. I just think we should make sure that we're killing it on the UX before we merge it. We don't really have a good enough handle on our data to define a baseline for usage and then compare it after this merges, so we just need to be really sure of ourselves up front. I haven't actually pulled down this code to test, so you may already have this covered - sorry if I'm making false issues.

I'm still bike shedding, but this is a hard UX problem to solve..  I'll keep thinking on ideas. (right now I'm imagining a "Waltz-Approved" indicator in the address bar, but I don't really love that idea)

**Comment by landakram** [comment]
The mechanics are similar to when site configs have `formOnly == true`, which we introduced for google apps since they add a random input every time the login form is submitted. For those sites, the button only shows on a page that has a login form since we need to submit the form instead of POSTing directly.

With universal Waltz, the button shows as soon as a login form is visible. I can't speak for all users of course, but when I use Waltz in its current form, I don't think about whether it is enabled on a site at all. I think: _Do I see the Waltz button? If so, then I can use Waltz. If not, then I can't._ This is probably because I use a mixture of sites that have both `formOnly == true` and `formOnly == false`. When I am navigating a site, something prompts my desire to log in. I then begin expressing my intention to log in by either clicking the Waltz button if it is visible, or clicking the first "log in/sign in" button I can find. In some cases, the Waltz button appears on the next page load (i.e. the login page).

In my usage of this branch, it's been similar — if I see the Waltz button, then I know I can log in with Waltz. The consistency of the button element is important for this. In expressing my intention to log in, the Waltz button appears, and then I understand I can use Waltz to log in instead of passwords. 

@jessepollak and I have also been talking about making Waltz more obvious as users move through expressing their intention to log in. I've been trained to look in the top right corner for the waltz button, but it's more natural for people to be looking for/at the login form itself when trying to log in.  I think we should make Waltz more prominent on the form, so users associate Waltz with the act of logging in and out. Haven't come up with any concrete designs yet, but I'm sure Jesse could say a little bit more about that.

**Comment by jessepollak** [comment]
Shipping this.

**Pull request merged**
