### PR TITLE
Improving credential input

### PR DESCRIPTION
**Pull request by jessepollak**
OK, so I've started thought on this UX.

Sceenshots:

screen shot 2013-10-11 at 6 21 13 pm

screen shot 2013-10-11 at 6 21 33 pm

The UI isn't there, but I think that this is the right UX.

TODO:
- ~~capture tab in form fields~~
- ~~clean up the code~~

### CODE REVIEW

**Comment by josephwegner** [comment]
I like it.

Things to think about:
- how do I dismiss this thing if I don't want to use clef?
- how do we make this less painful on registration forms?

**Comment by jessepollak** [comment]
TODO:
- [ ] restyle to fit with Waltz design patterns
- [ ] extend to work with registration (maybe?)

**Comment by jessepollak** [comment]
Merging.

**Comment by josephwegner** [comment]
Are these two TODOs done?  https://github.com/landakram/waltz/pull/22#issuecomment-26202947

I haven't pulled to check, but was just noticing that they are still unchecked in the comment.

**Pull request merged**
