### PR TITLE
Adds site config for Hipchat logins

### LINKED ISSUE #332: Hipchat
Please allow me to use Waltz to login to Hipchat

https://www.hipchat.com/

### PR DESCRIPTION
**Pull request by ninjapanzer**
Basically used the dropbox site config as a template for this. Hipchats login is not terribly complicated

To Resolve #332

### CODE REVIEW

**Comment by jessepollak** [comment]
This looks good. 

One question: is there a reason you duplicate `"https://www.hipchat.com/sign_in"` in the URLs section and add `"https://www.hipchat.com"`?

**Comment by ninjapanzer** [comment]
I didn't formally understand the `urls` section at first. As I modeled this from the dropbox config I think I just took things too literally.

**Comment by jessepollak** [comment]
Yeah, the configs can be a little confusing. If you'd remove those two URLs, I'll merge it in!

**Comment by ninjapanzer** [comment]
Already done in c8f6ee9 :)

**Comment by jessepollak** [comment]
Ah, somehow I missed that — merged!

**Pull request merged**
