### PR TITLE
Headless tests

### PR DESCRIPTION
**Pull request by josephwegner**
Now we can run tests on Travis!

I need to find a way to get travis to run on commits to develop, but not compile the site_configs

### CODE REVIEW

**Comment by jessepollak** [comment]
LGTM.

Does this use Grunt to include the files that we want to test or do we still have to add them to SpecRunner.html manually? Grunt would be preferred for sure.

**Comment by josephwegner** [comment]
I believe it uses grunt. You had already set it up, so I'm not 100% sure. But I think so.—

**Comment by jessepollak** [comment]
Ha, no I just included them because I couldn't get Jasmine to work. I think
now I could tweak this to work with Grunt now. I can do it this weekend
maybe.

**Comment by josephwegner** [comment]
@jessepollak Removed SpecRunner.html.  I'm going to test a few more things, and then I will merge this PR in.

**Comment by josephwegner** [comment]
@jessepollak Merged in.

However, it seems that we're getting a bunch of errors from Foundation.  The spec tests still pass, but there's a bunch of ugly red messages whenever jasmine runs.  [This StackOverflow question](http://stackoverflow.com/questions/8996852/load-and-execute-order-of-scripts) seems to indicate that the errors might go away in 5.0.3.

I know very little of what/how/why/where we're using Foundation, but could you look into bumping us up into 5.0.3?  I'm guessing it's a simple overwrite, but I don't know what quirks to look for to make sure nothing breaks.

**Pull request merged**
