### PR TITLE
Switch to using configs and manual form submit

### PR DESCRIPTION
**Pull request by jessepollak**

### CODE REVIEW

**Comment by jessepollak** [comment]
I currently have this working on Facebook, hooray!

**Comment by josephwegner** [comment]
Very nice.  Code looks good - merge away.  :+1:

**Comment by josephwegner** [comment]
I like that you're using the input name for the selector.  I was originally thinking we would use XPath, but that's probably way overkill.

**Comment by jessepollak** [comment]
One thing which will be _hard_ with this new POSTing method is redirecting to the proper page.

**Comment by jessepollak** [comment]
I added a redirect field, which works for Google. Will need to see how we need to adapt that as we bring on more sites.

What's the logout cookie for google @josephwegner ?

**Pull request merged**
