### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TkTech**
https does not work for getwaltz.com

### CODE REVIEW

**Comment by jessepollak** [comment]
Thanks :)

**Comment by josephwegner** [comment]
@jessepollak Should we get one of those free SSL certs, just so we can give off a secure vibe on getwaltz.com?

**Comment by jessepollak** [comment]
Yes that'd be naice.

**Comment by josephwegner** [comment]
I'm an idiot.  It's Github Pages. We can't add an SSL certificate.

**Comment by jessepollak** [comment]
True.

**Comment by lolux** [comment]
@josephwegner Happy to donate the space on my 1&1 cloud server and set up the free startcom cert if you gents decide to move away from Pages.

**Pull request merged**
