### PR TITLE
Starts styling the credentials 

### PR DESCRIPTION
**Pull request by jessepollak**
Looks much more inline with things.

### CODE REVIEW

**Comment by jessepollak** [comment]
screenshot 2013-11-01 20 53 48

**Comment by josephwegner** [comment]
This looks **really** great.  My only critique is that I don't think the waltz logo looks very good on a black background.  I think the lines of the tuxedo don't have enough padding from the edge of the logo, so the whole thing feels a bit cramped.  I think that if I didn't already know what the Waltz logo was, I wouldn't understand that logo.  I'm not really sure what I'm suggesting as a solution, but that is how I feel, anyways.

I also think the black background makes the form feel cramped.  I don't actually think it looks better, but lightening the background color makes the form feel a lot more open.

screen shot 2013-11-02 at 8 32 02 am

**Comment by jessepollak** [comment]
I'll keep on experimenting with it.

**Comment by jessepollak** [comment]
I just added a little more spacing, but I'm not going to put more time into this until we have more user feedback.

**Pull request merged**
