### PR TITLE
NY Times

### PR DESCRIPTION
**Pull request by lolux**
Ready to roll.

(Not sure why, but setting `"formOnly": true,` did not yield the expected result. Trading this for the new `match` parameter works, however.)

### CODE REVIEW

**Comment by landakram** [comment]
Hmm what was happening with `formOnly`?

**Comment by landakram** [comment]
I added an issue for `formOnly`. Merging this in. Alright @lolux!

**Comment by jessepollak** [comment]
@lolux, why did you add a match param to this config? Do they do some sort of bot sniffing like google?

**Comment by lolux** [comment]
Trial and error. I couldn't get `formOnly` to work in testing, but `match` worked.

**Comment by jessepollak** [comment]
Sweet, just pushed a fix, which makes this better.

**Pull request merged**
