### PR TITLE
exclude help.github.com

### PR DESCRIPTION
**Pull request by lolux**
Applies new match pattern parameter to exclude the `help` subdomain

### CODE REVIEW

**Comment by josephwegner** [comment]
@lolux This seems to work fine, but why do we want to remove the help.github.com subdomain? It seems that that would be a common place that people would want to log in from.

Furthermore, if we're removing help.github.com, why not remove status.github, developer.github, training,github, or shop.github?

**Comment by lolux** [comment]
The "problem" I am trying to solve is that, despite being logged in at github.com, the Waltz login button displays when user visits help.github.com. I wasn't aware that the other subdomains existed. (Duuuude, who has been holding out on me—training.github.com is exactly what I need! :-).

Hmm, okay. I think we need some distinctions for situations like this one where a site has multiple sub-sites, some that share the same credential as the main site and some that either are content only or have a different credential. Here's a first draft based on the situations I've seen so far:
1. If a sub-domain does not display a log in form or log in link, or if it does not use the same credential as the main site, then do not show the Waltz button. So, with Github, do not display Waltz button on help.github.com, training.github.com, or shop.github.com; for, none of those sites use the same credential as github.com, nor do they display a login link or form.
2. If a sub-domain does not share the same credential as the main site but does have a login form, then show the Waltz button—but do so using a second .json. See RunningWarehouse for an example. Many e-commerce sites like RW have a forum on a subdomain that takes a different credential than the one used on the main site.
3. If a sub-domain does share the same credential as the main site and requires a separate log in for that sub-domain (i.e., in cases such as RepublicWireless.com where the credential for the forum is the same as the main site but requires a second log in nonetheless), then show the Waltz button on both site using one .json with two site objects.

**Comment by josephwegner** [comment]
Ah, sorry, I was misunderstanding the issue.  I didn't realize the Waltz logo showed regardless of the login state.  This is a good PR, then.

I like (1) and (2) of your guidelines, but not (1).  I think part of the magic of Waltz is being able to log in on pages that don't actually have a login form.  That was my original issue with this PR - it's nice to be able to log in to Github form help.github.com.  But, only if it actually works :)

**Comment by josephwegner** [comment]
I'll do some more testing on this now that I forgot what I already did, and then I'll merge.  Thanks!

**Comment by josephwegner** [comment]
@lolux It looks like the same issue occurs on status.github.com.  Could you add that to the excludes, and then this is good to merge.

**Comment by lolux** [comment]
Okay. . .

**Pull request merged**
